---
- name: Install Postfix
  package: name=postfix state=latest

- name: Enable Postfix
  service: name=postfix state=started enabled=yes

- name: Backup configuration
  shell: cp /etc/postfix/main.cf /etc/postfix/main.cf.{{ postfix_backup_multiple | ternary("`date -Iseconds`", "backup") }}
  when: postfix_backup or postfix_backup_multiple

- name: Add header 1 to configuration file
  lineinfile:
    dest: /etc/postfix/main.cf
    regexp: '# Last modified:'
    state: present
    insertbefore: BOF
    line: "# Last modified: {{ ansible_date_time.date }}\n"

- name: Add header 2 to configuration file
  lineinfile:
    dest: /etc/postfix/main.cf
    regexp: 'managed by [aA]nsible'
    state: present
    insertbefore: BOF
    line: "# This file is managed by Ansible"

- name: Check Postfix config option
  shell: "postconf -h \"{{ item.key }}\" | grep \"^{{ item.value | regex_escape }}$\""
  ignore_errors: true
  changed_when: false
  loop: "{{ postfix_conf | dict2items }}"
  register: postconf_check

- name: Configure Postfix
  command: "postconf -e \"{{ item.item.key }}={{ item.item.value }}\""
  ignore_errors: true
  notify: check restart postfix
  when: item.rc != 0
  loop: "{{ postconf_check.results }}"
